import spidermanReview1 from './assets/spider-man-review1.jpg';
import spidermanReview2 from './assets/spider-man-review2.jpg';

import overwatchReview1 from './assets/overwatch-review1.jpg';
import overwatchReview2 from './assets/overwatch-review2.jpg';

import codReview1 from './assets/cod-review1.jpg';
import codReview2 from './assets/cod-review2.jpg';

import cs2Review1 from './assets/cs2-review1.jpg';
import cs2Review2 from './assets/cs2-review2.jpg';

import leagueReview1 from './assets/league-review1.jpg';
import leagueReview2 from './assets/league-review2.jpg';

import donkeyKongReview1 from './assets/donkey-kong-review1.png';
import donkeyKongReview2 from './assets/donkey-kong-review2.jpg';

const data = [
    {
        game: "spiderman",
        name: "Spiderman",
        title: "Marvel's Spider-Man for PS4 - A Web-Slinging Triumph",
        paragraph1: "Marvel's Spider-Man for PS4 is a triumphant web-slinging adventure that brilliantly captures the essence of the beloved superhero. Developed by Insomniac Games, this action-packed title catapults players into the shoes of Peter Parker as he swings through the bustling streets of New York City. With its engaging narrative, dynamic combat mechanics, and breathtaking open-world, Spider-Man delivers an unparalleled gaming experience that will leave players feeling like a true hero.",
        paragraph2: "Marvel's Spider-Man excels not only in storytelling but also in gameplay. Swinging through the city with the intuitive web-slinging mechanics is an absolute joy, creating a sense of exhilarating freedom. Moreover, the combat mechanics are fluid and satisfying, offering players a diverse set of moves and gadgets to dispatch enemies creatively. The open-world New York City is beautifully realized, packed with side quests and activities that provide plenty of content beyond the main story, ensuring players always have something exciting to do.",
        paragraph3: "In conclusion, Marvel's Spider-Man for PS4 is a resounding success and a must-play for fans of the web-slinging superhero. Its engaging narrative, seamless gameplay mechanics, and stunning open-world design come together to deliver an unforgettable gaming experience. Insomniac Games has done justice to the iconic character, making this title a standout in the realm of superhero video games. Whether you're a devoted Spider-Man fan or just looking for an exceptional action-adventure, this game will undoubtedly swing its way into your heart.",
        imageURL1: spidermanReview1,
        imageURL2: spidermanReview2, 
        commentTitle1:"A Perfect Tribute to Our Friendly Neighborhood Hero!",
        commentTitle2: "Overhyped and Underwhelming",
        commentAuthor1: "SpideyFan22",
        commentAuthor2: "NotImpressedGamer",
        commentBody1: "Your review of Marvel's Spider-Man for PS4 is spot on! As a lifelong Spider-Man fan, I couldn't have asked for a better gaming experience. The captivating storyline took me on an emotional rollercoaster, and I truly felt connected to Peter Parker's struggles and triumphs. The web-swinging mechanics are simply exhilarating, and it's evident that Insomniac Games put a lot of effort into making it feel effortless and natural. With a well-designed open-world and an array of exciting side quests, I found myself lost in the bustling streets of New York City for hours. This game is a true tribute to our favorite superhero, and I can't recommend it enough to fellow Spidey enthusiasts!",
        commentBody2: "I hate to be the dissenting voice here, but I found Marvel's Spider-Man for PS4 to be overhyped and ultimately underwhelming. While the graphics and open-world design were visually appealing, the storyline failed to engage me as much as I had hoped. I felt disconnected from Peter Parker's journey, and the characters lacked depth, making it difficult to invest emotionally. Additionally, while web-swinging was fun initially, I grew tired of the repetitive combat and lack of complexity in the gameplay mechanics. It's a decent game for casual players, but as a long-time fan of Spider-Man, I expected more from this title.",
        active01: 4000,
        active02: 1500,
        active03: 9000,
        active04: 12000,
        active05: 6500,
        active06: 8500,
        active07: 3000,
        under10: 400,
        ten50: 300,
        fifty100: 300,
        hundred500: 200,
        fiveHundred1000: 278,
        over1000: 189,
    },

    {
        game: "overwatch",
        name: "Overwatch",
        title: "Overwatch - A Dynamic Multiplayer Game",
        paragraph1: "Overwatch, the brainchild of Blizzard Entertainment, has proven itself to be a dynamic and enduring multiplayer triumph. This first-person shooter delivers a captivating experience by weaving together diverse heroes, stunning visuals, and fast-paced gameplay. Set in a vibrant world with an array of visually striking maps, Overwatch boasts an impressive cast of characters, each with unique abilities and roles that contribute to the game's emphasis on teamwork and strategy.",
        paragraph2: "The heart of Overwatch lies in its ever-expanding roster of heroes, currently boasting over 30 characters, each offering a distinct playstyle. From agile and elusive Tracers to powerful and commanding Reinhardts, players have a wide range of options to suit their preferences. The game's emphasis on team composition and synergy makes every match an exciting challenge. Effective communication and coordination among teammates are key to achieving victory, adding a layer of depth and camaraderie that sets Overwatch apart from traditional shooters.",
        paragraph3: "Moreover, Blizzard's commitment to regular updates and community engagement has kept Overwatch fresh and engaging throughout the years. Seasonal events, limited-time game modes, and new hero additions have all contributed to the game's ever-evolving meta. The constant stream of content ensures that there's always something new to explore and master, keeping players invested in the game for the long haul. Overall, Overwatch stands as a benchmark in the world of multiplayer shooters, offering an unrivaled blend of diverse gameplay, compelling characters, and an ever-evolving experience that keeps fans coming back for more.",
        imageURL1: overwatchReview1,
        imageURL2: overwatchReview2, 
        commentTitle1:" Lost its Appeal Over Time",
        commentTitle2: " A Multiplayer Gem!",
        commentAuthor1: "LoneGamer87",
        commentAuthor2: "OverwatchFanatic88",
        commentBody1: "While I initially fell in love with Overwatch's diverse hero roster and fast-paced gameplay, my enthusiasm waned over time. The game felt repetitive, and the constant balancing changes disrupted the meta too frequently, making it hard to settle into a preferred playstyle. Moreover, communication in matches often proved to be a challenge, as many players preferred to stay silent or toxic. As someone who enjoys solo play, I found it increasingly difficult to maintain interest due to the game's heavy reliance on team coordination. While Overwatch undeniably offers a unique and exciting experience, it just couldn't hold my attention in the long run, leaving me searching for a more solo-friendly and consistent multiplayer title.",
        commentBody2: "This review perfectly captures the essence of Overwatch! As a dedicated fan of the game since its release, I can attest to its brilliance. The vast array of unique heroes and their abilities make each match a thrilling and strategic experience. Whether you prefer being on the front lines, providing crucial support, or dishing out damage from afar, there's a hero for every playstyle. The constant updates and events keep the game fresh, and Blizzard's commitment to engaging with the community makes it even more enjoyable. Overwatch's dynamic gameplay and emphasis on teamwork have turned it into a multiplayer gem that continues to shine bright even years after its release.",
        active01: 8500,
        active02: 6500,
        active03: 3000,
        active04: 12000,
        active05: 1500,
        active06: 4000,
        active07: 9000,
        under10: 200,
        ten50: 300,
        fifty100: 278,
        hundred500: 189,
        fiveHundred1000: 300,
        over1000: 400,
    },

    {
        game: "cod",
        name: "Call of Duty Mobile",
        title: "Action-Packed Thrills Await: A Review of Call of Duty Mobile",
        paragraph1: "Call of Duty Mobile brings the heart-pounding action of the beloved franchise right to your fingertips. As a long-time fan of the series, I was both excited and skeptical about experiencing the intense gameplay on a mobile platform. However, I was pleasantly surprised by the game's seamless transition to mobile devices. The controls are surprisingly intuitive, offering a range of customization options to suit individual playstyles. Whether it's engaging in adrenaline-pumping multiplayer battles or embarking on captivating solo missions, Call of Duty Mobile keeps players immersed in its fast-paced world. The extensive array of weapons, character classes, and unlockable content adds depth to the gameplay, ensuring hours of addictive fun.",
        paragraph2: "One of the standout features of Call of Duty Mobile is its impressive graphics and smooth performance. The visuals are surprisingly sharp and detailed for a mobile game, making every firefight feel incredibly lifelike. The game's optimization ensures a consistent frame rate, even on older devices, enhancing the overall gaming experience. Additionally, the sound design is top-notch, with realistic gunfire, explosions, and voiceovers that further immerse players in the virtual battlefield. From the stunning maps inspired by iconic Call of Duty locations to the thrilling game modes like Battle Royale and Zombies, there is always something new and exciting to explore, keeping players hooked for the long haul.",
        paragraph3: "As with any free-to-play mobile game, microtransactions are present in Call of Duty Mobile. While they are not overly intrusive and can be entirely avoided, some players might find certain premium items tempting. Nevertheless, the game's fair approach to monetization ensures that one's skill and strategy prevail in the game, not the depth of one's wallet. Frequent updates, seasonal events, and a dedicated development team committed to the community further enhance the game's longevity and replayability.",
        imageURL1: codReview1,
        imageURL2: codReview2, 
        commentTitle1:"Spot on Review",
        commentTitle2: "Almost There, But Not Quite",
        commentAuthor1: "FPSFanatic91",
        commentAuthor2: "OldGamerProblems",
        commentBody1: "Call of Duty Mobile truly lives up to its name, offering exhilarating action in the palm of your hand. The review perfectly captures the game's seamless transition to mobile platforms and how it keeps players hooked with its engaging gameplay. The graphics are stunning, and the various game modes add depth to the experience. I can't get enough of it, and I highly recommend it to all fellow FPS enthusiasts!",
        commentBody2: "While the review highlights the impressive aspects of Call of Duty Mobile, I must admit there are a couple of downsides. As someone who's played the series for years, I did find the controls a bit challenging to master on a smaller screen. Additionally, the review doesn't delve into the occasional performance issues, particularly on older devices. Despite these concerns, it's still an enjoyable game with tons of potential, but some players might need some time to adjust.",
        active05: 1500,
        active03: 3000,
        active06: 4000,
        active02: 6500,
        active01: 8500,
        active07: 9000,
        active04: 12000,
        hundred500: 189,
        under10: 200,
        ten50: 300,
        fiveHundred1000: 300,
        fifty100: 278,
        over1000: 400,

    },

    {
        game: "cs2",
        name: "Counter-Strike: Global Offensive 2",
        title: "Counter-Strike: Global Offensive 2 (CS:GO)  - A Dated and Frustrating Experience",
        paragraph1: "Counter-Strike: Global Offensive, or CS:GO, once hailed as a legendary game, now feels like a dated and frustrating experience. Developed by Valve, this first-person shooter has failed to evolve significantly since its release in 2012, leaving players craving for more innovation and improvements. CS:GO's repetitive gameplay, toxicity, and lack of meaningful updates have resulted in a dwindling player base and an overall lackluster experience.",
        paragraph2: "One of the most significant issues with CS:GO is its stagnant gameplay. While the core mechanics remain solid, the lack of fresh content and gameplay updates has led to a repetitive and tiresome experience. The game's reliance on precise aiming and recoil control can be frustrating for newcomers, as veteran players dominate matches with ease, leaving little room for skill growth or fair competition. Furthermore, the matchmaking system often places players with experienced opponents, leading to imbalanced matches and discouraging new players from sticking around.",
        paragraph3: "The CS:GO community has long struggled with toxic behavior, tarnishing the overall gaming experience. Verbal abuse, griefing, and cheating are rampant, contributing to a hostile environment that drives away players seeking a more enjoyable and welcoming atmosphere. While Valve attempts to address these issues with occasional updates and bans, the toxic culture remains pervasive, making it difficult for players to fully enjoy the game.",
        imageURL1: cs2Review1,
        imageURL2: cs2Review2, 
        commentTitle1:"Still My Go-To Shooter!",
        commentTitle2: "A Dying Game with Toxicity Issues",
        commentAuthor1: "CS_Master88",
        commentAuthor2: "FrustratedGamer23",
        commentBody1: "As someone who has been playing CS:GO since its early days, I must respectfully disagree with this review. CS:GO's timeless gameplay, built on precise aiming and tactical decision-making, is what keeps me coming back for more. While some may find the game challenging, it's that very challenge that makes it rewarding and satisfying. The competitive nature of CS:GO has helped me grow as a player and forge lasting friendships within the community. Sure, there may be some toxicity, but every online game has its bad apples. Overall, CS:GO remains my go-to shooter, and I believe it still has plenty to offer for those who appreciate its classic mechanics and competitive spirit.",
        commentBody2: "I couldn't agree more with this review; CS:GO is becoming a disappointing experience. The lack of meaningful updates and innovation has left the game feeling stale and repetitive. As a casual player, I find it increasingly frustrating to face skilled veterans who dominate matches, leaving no room for improvement or fun. Additionally, the toxicity within the community is overwhelming, making it difficult to enjoy matches without encountering rude and offensive behavior. I used to love CS:GO, but the declining player base and toxic atmosphere have pushed me away from the game. I hope Valve addresses these issues soon; otherwise, CS:GO may continue on its downward spiral.",
        active05: 9000,
        active03: 1500,
        active06: 4000,
        active02: 6500,
        active01: 3000,
        active07: 8500,
        active04: 12000,
        ten50: 300,
        fiveHundred1000: 300,
        fifty100: 278,
        hundred500: 189,
        under10: 200,
        over1000: 400,

    },

    {
        game: "lol",
        name: "",
        title: "League of Legends - A Dichotomy of Thrills and Frustrations",
        paragraph1: "League of Legends, developed by Riot Games, is undeniably a MOBA that has made a lasting impact on the gaming landscape. Its extensive champion roster, strategic gameplay, and engaging esports scene have earned it a dedicated following and a place in the annals of competitive gaming. However, with its complexities and ever-evolving meta, the game also comes with its fair share of frustrations that may deter some players from fully embracing its brilliance.",
        paragraph2: "One of League of Legends' greatest strengths lies in its vast and diverse pool of champions. The game offers an array of unique playstyles and abilities, ensuring that every player can find a champion that suits their preferences. Mastering a favorite champion and experiencing their full potential is deeply satisfying and encourages players to continuously improve their skills. Furthermore, the competitive aspect of the game is exhilarating, and the coordination required for success promotes a sense of teamwork and camaraderie among players.",
        paragraph3: "On the other hand, the game's steep learning curve and intricate mechanics can be overwhelming for newcomers. The necessity of understanding not only one's chosen champion but also the intricate interactions with other champions and items can be a daunting task. Additionally, the community's competitive nature can lead to a toxic environment, where negative behavior and harassment can detract from the overall enjoyment of the game. Furthermore, the frequent updates and balance changes can sometimes disrupt the game's balance and leave players struggling to adapt.",
        imageURL1: leagueReview1,
        imageURL2: leagueReview2, 
        commentTitle1:"A Thrilling Adventure Worth the Effort!",
        commentTitle2: "A Dying Game with Toxicity Issues",
        commentAuthor1: " LoLenthusiast123",
        commentAuthor2: "FrustratedGamer23",
        commentBody1: "As a long-time player of League of Legends, I can confidently say that the game's complexities and challenges are what make it so enticing. The vast selection of champions offers an exciting range of playstyles, ensuring that every match feels unique. While the learning curve can be steep, the feeling of mastering a champion and contributing to a well-coordinated team victory is unparalleled. The competitive nature of League of Legends keeps me coming back for more, as each match presents a new opportunity to improve and showcase my skills. Despite the occasional frustrations, the thrill of the game and the camaraderie within the community make League of Legends an adventure worth embarking on.",
        commentBody2: "I recently started playing League of Legends, and I must admit, it has been an overwhelming and disheartening experience. The vast array of champions and intricate mechanics are difficult to grasp for a newcomer like myself. I find myself frequently struggling to keep up with more experienced players, leading to a sense of frustration and inadequacy. Moreover, the toxic behavior from some players further dampens the enjoyment of the game. While I recognize that League of Legends has its merits, I can't help but feel discouraged and hesitant to invest more time in a gaming environment that often feels hostile and unwelcoming to newcomers like me.",
        active07: 3000,
        active02: 6500,
        active01: 9000,
        active06: 12000,
        active04: 1500,
        active05: 4000,
        active03: 8500,
        hundred500: 400,
        fifty100: 300,
        under10: 300,
        fiveHundred1000: 189,
        ten50: 278,
        over1000: 200,

    },

    {
        game: "donkeyKong",
        name: "Donkey Kong",
        title: "Donkey Kong - Watching Paint Dry is More Interesting",
        paragraph1: "Donkey Kong, a classic arcade game from the 1980s, falls short of the enjoyable and engaging experience one might expect from a timeless title. Developed by Nintendo, this platformer has not aged well, leaving players with an outdated and frustrating gameplay experience that fails to live up to modern gaming standards. While it holds nostalgic value for some, the game's simplistic mechanics, repetitive gameplay, and lack of depth make it a lackluster choice for contemporary gamers.",
        paragraph2: "One of the main issues with Donkey Kong is its lack of complexity and variety in gameplay. The levels are limited and repetitive, offering little innovation as players progress through the game. The simplistic mechanics, while groundbreaking at the time of its release, feel dated and shallow compared to the immersive experiences offered by modern platformers. As players encounter the same obstacles and challenges repeatedly, the initial thrill quickly gives way to monotony, leaving little incentive to continue playing.",
        paragraph3: "Furthermore, the game's difficulty level can be off-putting for many players. The unforgiving and challenging gameplay requires precise timing and coordination, making it frustratingly difficult for newcomers or casual gamers to progress. Additionally, the lack of save points or checkpoints amplifies the frustration, as players are forced to start from the beginning each time they fail. This antiquated design choice can lead to a sense of discouragement, pushing players away from the game rather than enticing them to conquer its challenges.",
        imageURL1: donkeyKongReview1,
        imageURL2: donkeyKongReview2, 
        commentTitle1:"A Dull and Dated Disappointment",
        commentTitle2: "Nostalgic Fun for Classic Gaming Enthusiasts!",
        commentAuthor1: "FrustratedGamer21",
        commentAuthor2: "RetroGamer1985",
        commentBody1: " I have to agree with the review on this one; Donkey Kong is a dull and dated disappointment. As a modern gamer accustomed to engaging and immersive gameplay, I found the simplistic mechanics and repetitive levels to be a major letdown. While I respect the game's historical significance, it lacks the depth and complexity that contemporary gamers seek. The frustrating difficulty level only adds to the disappointment, leaving little room for enjoyment or progress. Donkey Kong may have been groundbreaking in its time, but as a modern player, I couldn't help but feel disheartened by its lackluster experience.",
        commentBody2: "As someone who grew up in the '80s, Donkey Kong holds a special place in my heart, and I must respectfully disagree with this review. While I understand that the game may not appeal to modern gamers seeking complex and immersive experiences, Donkey Kong offers a nostalgic trip down memory lane for classic gaming enthusiasts like myself. Its simplistic gameplay and challenging levels remind me of the golden era of arcade gaming. The thrill of trying to rescue the damsel in distress from Donkey Kong's clutches never gets old, and it brings back fond memories of my early gaming days. For those who appreciate the history of gaming and want to relive the arcade era, Donkey Kong remains a timeless gem that should not be overlooked.",
        active05: 1500,
        active03: 3000,
        active06: 4000,
        active02: 6500,
        active01: 9000,
        active07: 8500,
        active04: 12000,
        hundred500: 278,
        fiveHundred1000: 189,
        over1000: 300,
        fifty100: 400,
        under10: 300,
        ten50: 200,

    }
]

export default data;
