import spidermanReview1 from './assets/spider-man-review1.jpg';
import spidermanReview2 from './assets/spider-man-review2.jpg';

import overwatchReview1 from './assets/overwatch-review1.jpg';
import overwatchReview2 from './assets/overwatch-review2.jpg';

import codReview1 from './assets/cod-review1.jpg';
import codReview2 from './assets/cod-review2.jpg';

import cs2Review1 from './assets/cs2-review1.jpg';
import cs2Review2 from './assets/cs2-review2.jpg';

import leagueReview1 from './assets/league-review1.jpg';
import leagueReview2 from './assets/league-review2.jpg';

import donkeyKongReview1 from './assets/donkey-kong-review1.png';
import donkeyKongReview2 from './assets/donkey-kong-review2.jpg';

const data = [
    {
        game: "spiderman",
        name: "Spiderman",
        title: "Marvel's Spider-Man for PS4 - A Web-Slinging Success",
        paragraph1: "Web-swinging through the city (which entails swinging, dashing forward, doing cool tricks in the air, running up and along walls and zipping to perches) is glorious. There's nothing quite like it in modern video games. In many ways it's the high-definition sequel to 2004's Spider-Man 2 and shares many of the same systems.",
        paragraph2: "In any case, combat is fun. There's a bunch of combos you can employ and they're all fairly simple to learn. Press square and you punch. Press and hold square and you punch an enemy into the air. Now you can punch them a few more times in the air or you can hold triangle to slam them to the ground. Or you could hold square to do a swing kick then follow that up with a series of punches. If you face off against an enemy with a riot shield, punch them once then dodge with circle and you'll slide between their legs so you can hit them from behind. If another enemy is across the street, tap triangle to web your way directly to them.",
        paragraph3: "For one thing, I liked it enough to finish it and I only started to get a little tired of it toward the end (and only with all the side content that non-reviewers can enjoy without the need to get a review published on time.) The story kept me hooked right up until the bitter end and when the credits rolled I couldn't wait for the sequel, which (depending on sales) seems all but inevitable.",
        imageURL1: spidermanReview1,
        imageURL2: spidermanReview2, 
        commentTitle1:"A Perfect Tribute to Spidey",
        commentTitle2: "Overhyped and Underwhelming",
        commentAuthor1: "SpideyFan22",
        commentAuthor2: "NotImpressedGamer",
        commentBody1: "Your review of Marvel's Spider-Man for PS4 is spot on! I love the way you discuss the combat",
        commentBody2: "I hate to be the negative voice here, but I found the game to be too boring at times",
        active01: 4000,
        active02: 1500,
        active03: 9000,
        active04: 12000,
        active05: 6500,
        active06: 8500,
        active07: 3000,
        under10: 400,
        ten50: 300,
        fifty100: 300,
        hundred500: 200,
        fiveHundred1000: 278,
        over1000: 189,
    },

    {
        game: "overwatch",
        name: "Overwatch",
        title: "Overwatch - A Fun Multiplayer Game",
        paragraph1: "Overwatch’s gameplay has remained almost entirely unchanged since launch and centres around taking and controlling points on the map or escorting payloads from one end of them to the other, all at the expense of the enemy team’s health bars. It’s a simple setup and not an altogether original one, but it’s the nuance found in how you go about winning each match that makes Overwatch so brilliant.",
        paragraph2: "Each team of six can be stitched together from the current pool of 32 heroes. Not only does each play differently and bring their own tricks to the party, but they also affect the other heroes on the ever-expanding roster with each new addition. Overwatch is a game bursting with character, not least displayed in the characters themselves. Blizzard has created a world where anything goes and everything flourishes.",
        paragraph3: "Overwatch is an incredible achievement in multiplayer shooter design. It bobs and weaves almost perfectly between being the quick-fix adrenaline hit you might want after a long day of work, and the thoughtful, strategic multiplayer experience that becomes the center of evening-long binges with friends. It might not have the most exhaustive list of maps and modes, but it provides nearly endless opportunities for exhilarating, coordinated play, and when you’re the one at the center of it, it feels like nothing else",
        imageURL1: overwatchReview1,
        imageURL2: overwatchReview2, 
        commentTitle1:" Lost its Appeal Over Time",
        commentTitle2: " A Multiplayer Gem!",
        commentAuthor1: "LoneGamer87",
        commentAuthor2: "OverwatchFanatic88",
        commentBody1: "While I initially fell in love with Overwatch, The new updates have ruined it for me. You`re being too positive",
        commentBody2: "This review perfectly captures the essence of Overwatch! A game with unending opportunities",
        active01: 8500,
        active02: 6500,
        active03: 3000,
        active04: 12000,
        active05: 1500,
        active06: 4000,
        active07: 9000,
        under10: 200,
        ten50: 300,
        fifty100: 278,
        hundred500: 189,
        fiveHundred1000: 300,
        over1000: 400,
    },

    {
        game: "cod",
        name: "Call of Duty Mobile",
        title: "Action-Packed Thrills Await: Call of Duty Mobile",
        paragraph1: "Amazingly, it works. Call of Duty: Mobile doesn’t come across like a deeply compromised or watered-down rendition of the age-old multiplayer format; it just feels like Call of Duty. And it looks like it too, running at a high frame rate and looking detailed and sharp on my iPhone 11 Pro Max.",
        paragraph2: "Call of Duty: Mobile has the same flow and cadence of combat as its counterparts on consoles and the PC; the same satisfying pop to a headshot or grisly tension of a knife to a back. It also has some of the same modes intact, including team deathmatch, the area-controlling Domination, and the delightful Gun Game, in which you try to be the first player to rack up one kill apiece with 20 different weapons.",
        paragraph3: "It’s meant for more casual play, and for more casual players too — it’s for the few spare minutes at the end of a lunch break, or a quick match while killing time. And it’s for the players who probably wouldn’t spend $60 on a new Call of Duty game, or don’t aspire to compete at a high level.",
        imageURL1: codReview1,
        imageURL2: codReview2, 
        commentTitle1:"Casual is right!",
        commentTitle2: "Almost There, But Not Quite",
        commentAuthor1: "FPSFanatic91",
        commentAuthor2: "OldGamerProblems",
        commentBody1: "I agree! I love playing cod mobile while my mom is buying groceries",
        commentBody2: "While the review highlights the impressive aspects of Call of Duty Mobile, It ignores the downsides",
        active05: 1500,
        active03: 3000,
        active06: 4000,
        active02: 6500,
        active01: 8500,
        active07: 9000,
        active04: 12000,
        hundred500: 189,
        under10: 200,
        ten50: 300,
        fiveHundred1000: 300,
        fifty100: 278,
        over1000: 400,

    },

    {
        game: "cs2",
        name: "Counter-Strike: Global Offensive 2",
        title: "Counter-Strike: Global Offensive 2 (CS:GO)  - A mixed Experience",
        paragraph1: "CS: GO's Bomb Scenario mode is a simple, yet enjoyable, twist on the standard multiplayer FPS setup, which opens up a ton of variability in each round. Another game mode, called Hostage, flips the tables and has the Terrorists defend a hostage, while the Counter-Terrorists attempt a rescue mission. CS: GO typically gets new mission-based modes with new operations. The current operation, Operation Hydra (released in May 2017) brought War Games, Wingman, and Weapons Expert modes to the game. These modes introduce twists on regular gameplay and affect the available weapons, the match objective, and the playable maps. These operations typically include a narrative-driven campaign, too.",
        paragraph2: "Aiming is accurate, but the damage system may require some adjustment. Basically, unless you use a rifle, you need to hit an enemy several times (in high-impact body areas) or many times (in the arm, leg, or stomach) to eliminate them. Reload times on more powerful weapons are also longer than what I originally anticipated. Note that your character's movement speed depends on the type of weapon you carry. So, in effect, you will be able to move more quickly equipped with a pistol, for example, than with a machine gun.",
        paragraph3: "If you have never played Counter Strike: GO before, it's worth giving it a shot despite its age. If you have played it and decided to leave for whatever reason, know that not much has changed. CS: GO is still a solid multiplayer FPS with a good variety of weapons, maps, and modes. However, despite the Panorama UI update, some maps are starting to look dull compared with those in more modern titles such as PUBG and Overwatch. And although CS: GO's esports following contributes to its prolonged success, the player community is not as welcoming as others.",
        imageURL1: cs2Review1,
        imageURL2: cs2Review2, 
        commentTitle1:"Still My Go-To FPS!",
        commentTitle2: "A Dying Game ",
        commentAuthor1: "CS_Master88",
        commentAuthor2: "FrustratedGamer23",
        commentBody1: "I Agree with this review. CS:GO's is a masterpiece that takes skill. If you disagree you`re a noob",
        commentBody2: "I must disagree; CS:GO is becoming a disappointing experience",
        active05: 9000,
        active03: 1500,
        active06: 4000,
        active02: 6500,
        active01: 3000,
        active07: 8500,
        active04: 12000,
        ten50: 300,
        fiveHundred1000: 300,
        fifty100: 278,
        hundred500: 189,
        under10: 200,
        over1000: 400,

    },

    {
        game: "lol",
        name: "",
        title: "League of Legends - A long lasting Icon",
        paragraph1: "Like most MOBAs, League of Legends’ main attraction is its five-on-five matches on its staple three-lane map. Called Summoner's Rift, this map is brightly and colorfully designed, and it creates a distinct playstyle with the way its dense brush allows you to conceal yourself and surprise enemies. I particularly love how the distinctive jungles on either side of the central river are filled with NPC monsters that give buffs to players who take a break from battle to go on the hunt – it’s a constant temptation to risk venturing into the other team’s territory to attempt to steal their buffs. The choice between engaging the other team directly or attacking their resources allows for interesting strategies and depth beyond simply fighting until one Champion or turret is dead.",
        paragraph2: "As free-to-play games go, League of Legends is a model of generosity. Though it doesn’t give everything away like Dota 2 does, it serves up a weekly rotating selection of 10 Champions for free, and you can purchase and play with any of the 117-character roster for a reasonable price of between two and eight dollars each. Yes, that adds up to a princely sum if you intend to buy every single character, but there’s no need to buy more than you intend to actually play. The Champion rotation is a nice way to try before you buy, and helped me to pace myself by learning just a few characters at a time.",
        paragraph3: "Even though you play on the same few maps with similar items, there’s so much depth and strategy going on that no two matches of League of Legends ever feel the same. It’s distinctive style encourages surprise attacks and frequent use of skill-shot powers, and its colorful art style makes everything pop on the screen. Learning how to make the most of its characters and to become an asset to a team is a long and challenging process, but once you’ve got it down, it’s incredibly satisfying to work together to destroy your enemies in this amazing MOBA",
        imageURL1: leagueReview1,
        imageURL2: leagueReview2, 
        commentTitle1:"So thrilling!",
        commentTitle2: "Too toxic",
        commentAuthor1: " LoLenthusiast123",
        commentAuthor2: "FrustratedGamer23",
        commentBody1: "As a long-time player of League of Legends, I have got to say that no other game compares. I agree, it is satisfying to destroy your enemies!",
        commentBody2: "Sure, the game is fun in principal but it`s way too toxic!",
        active07: 3000,
        active02: 6500,
        active01: 9000,
        active06: 12000,
        active04: 1500,
        active05: 4000,
        active03: 8500,
        hundred500: 400,
        fifty100: 300,
        under10: 300,
        fiveHundred1000: 189,
        ten50: 278,
        over1000: 200,

    },

    {
        game: "donkeyKong",
        name: "Donkey Kong",
        title: "Donkey Kong - a retro Masterpiece",
        paragraph1: "Donkey Kong is an arcade high score attack game and also the first jumping platform title to be released. Mario tries to save Pauline from the giant ape Donkey Kong across four different stages that greatly change how a player needs to approach each challenge in order to be successful. The variety is welcome and helps keep the experience fresh. As the player progresses, the levels loop and the difficulty increases.",
        paragraph2: "Despite some issues, Arcade Archives Donkey Kong is the real deal. The long wait to play a true home version of the arcade classic that made Nintendo a household name is finally over. Donkey Kong has so much historical significance that it's impossible for me not to recommend it. As stated before, it was the first jumping platformer and it introduced some of gaming's biggest characters in the way of its star Donkey Kong and Mario.",
        paragraph3: "Donkey Kong is a true classic that should be played by anyone with an interest in gaming history. It's one of the most competitive and challenging classic arcade titles even to this day and without it, I'd argue this website wouldn't even exist. Sure, Donkey Kong may show its age a bit, but the gameplay still holds up and can be very addictive. Add in the fact that we still don't know for sure who owns the code to this original game and I would call it a must buy. Who knows if this release could just be ripped from the eShop as some contract expires. In any case, what are you waiting for? You have a future New Donk City Mayor to save!",
        imageURL1: donkeyKongReview1,
        imageURL2: donkeyKongReview2, 
        commentTitle1:"A  Disappointment",
        commentTitle2: "Nostalgic Fun!",
        commentAuthor1: "FrustratedGamer21",
        commentAuthor2: "RetroGamer1985",
        commentBody1: " I have to disagree with the review on this one. Donkey Kong is a Boring game that's for boomers ",
        commentBody2: "As someone who grew up in the '80s, Donkey Kong holds a special place in my heart you knoked the review out of the park!",
        active05: 1500,
        active03: 3000,
        active06: 4000,
        active02: 6500,
        active01: 9000,
        active07: 8500,
        active04: 12000,
        hundred500: 278,
        fiveHundred1000: 189,
        over1000: 300,
        fifty100: 400,
        under10: 300,
        ten50: 200,

    }
]

export default data;
